export interface HeadlineOption {
  id: string;
  category: "⚡ Urgência & Escassez" | "💰 Desconto & Economia" | "👑 Exclusividade & Grupo VIP" | "🚀 Lançamento & Novidade" | "🛡️ Garantia & Confiança";
  headline: string;
  subheadline: string;
  tag: string;
}

export const HEADLINE_CATEGORIES = [
  "all",
  "⚡ Urgência & Escassez",
  "💰 Desconto & Economia",
  "👑 Exclusividade & Grupo VIP",
  "🚀 Lançamento & Novidade",
  "🛡️ Garantia & Confiança",
] as const;

export const HIGH_CONVERSION_HEADLINES: HeadlineOption[] = [
  // 1. Urgência & Escassez (10 modelos)
  {
    id: "urg_1",
    category: "⚡ Urgência & Escassez",
    tag: "Tempo Limitado",
    headline: "⚡ OFERTA RELÂMPAGO: Válida somente enquanto durarem os estoques!",
    subheadline: "Restam poucas unidades disponíveis com essa condição especial. Garanta a sua agora mesmo antes que encerre!",
  },
  {
    id: "urg_2",
    category: "⚡ Urgência & Escassez",
    tag: "Últimas Horas",
    headline: "⏳ ÚLTIMAS HORAS: Garanta o seu com desconto antes da virada do lote!",
    subheadline: "O cronômetro está rodando. Ao finalizar este lote, os preços voltarão ao valor normal sem aviso prévio.",
  },
  {
    id: "urg_3",
    category: "⚡ Urgência & Escassez",
    tag: "Queima de Estoque",
    headline: "🔥 QUEIMA DE ESTOQUE: Pouquíssimas unidades restantes com preço de custo!",
    subheadline: "Liquidação total autorizada direto da distribuidora. Aproveite essa chance única enquanto ainda há estoque.",
  },
  {
    id: "urg_4",
    category: "⚡ Urgência & Escassez",
    tag: "Alerta de Vagas",
    headline: "🚨 ATENÇÃO: Restam menos de 10 pedidos liberados com essa condição!",
    subheadline: "Devido à alta demanda em nossos canais, os pedidos serão atendidos rigorosamente por ordem de chegada.",
  },
  {
    id: "urg_5",
    category: "⚡ Urgência & Escassez",
    tag: "Apenas Hoje",
    headline: "⌛ CONDIÇÃO EXCLUSIVA DE HOJE: Aproveite antes de encerrar o expediente!",
    subheadline: "Preço promocional negociado exclusivamente para pedidos realizados e confirmados ainda hoje.",
  },
  {
    id: "urg_6",
    category: "⚡ Urgência & Escassez",
    tag: "Primeiros Compradores",
    headline: "🏃‍♂️ QUEM CHEGAR PRIMEIRO LEVA: Desconto recorde para os próximos pedidos!",
    subheadline: "Condição ultra especial liberada apenas para as próximas pessoas que clicarem no botão abaixo.",
  },
  {
    id: "urg_7",
    category: "⚡ Urgência & Escassez",
    tag: "Último Lote",
    headline: "📦 ÚLTIMO LOTE DISPONÍVEL: A próxima remessa terá reajuste de tabela!",
    subheadline: "Garanta o valor promocional da remessa atual com envio imediato e rastreio direto no seu WhatsApp.",
  },
  {
    id: "urg_8",
    category: "⚡ Urgência & Escassez",
    tag: "Válido até 23h59",
    headline: "⏰ VÁLIDO SOMENTE ATÉ ÀS 23H59: Link promocional expira automaticamente!",
    subheadline: "Não perca essa oportunidade. Nosso sistema encerrará o cupom de desconto à meia-noite em ponto.",
  },
  {
    id: "urg_9",
    category: "⚡ Urgência & Escassez",
    tag: "Oferta Explosiva",
    headline: "💣 OFERTA EXPLOSIVA: Preço reduzido apenas para quem entrar agora!",
    subheadline: "Desconto agressivo aplicado direto na página. Toque no botão e finalize em menos de 1 minuto.",
  },
  {
    id: "urg_10",
    category: "⚡ Urgência & Escassez",
    tag: "Quase Esgotado",
    headline: "🛑 QUASE ESGOTADO: Não deixe para depois e garanta a sua unidade hoje!",
    subheadline: "Mais de 90% do estoque reservado. Clique abaixo para garantir a sua unidade antes que acabe.",
  },

  // 2. Desconto & Economia (10 modelos)
  {
    id: "desc_1",
    category: "💰 Desconto & Economia",
    tag: "Maior Desconto",
    headline: "💰 SUPER DESCONTO LIBERADO: Economize de verdade no seu pedido!",
    subheadline: "Compre direto da fonte sem intermediários. O melhor preço com a máxima qualidade garantida.",
  },
  {
    id: "desc_2",
    category: "💰 Desconto & Economia",
    tag: "Menor Preço",
    headline: "🏷️ O MENOR PREÇO DO ANO: Condição imbatível direto no WhatsApp!",
    subheadline: "Pesquise e comprove: cobrimos qualquer oferta da categoria com atendimento humano e envio rápido.",
  },
  {
    id: "desc_3",
    category: "💰 Desconto & Economia",
    tag: "Mega Liquidação",
    headline: "📉 MEGA LIQUIDAÇÃO: De valor cheio por uma fração imperdível!",
    subheadline: "Aproveite a margem reduzida para renovar seus pedidos com a maior economia do mercado.",
  },
  {
    id: "desc_4",
    category: "💰 Desconto & Economia",
    tag: "Combo Especial",
    headline: "🎁 COMBO ESPECIAL: Leve qualidade premium pagando muito menos!",
    subheadline: "Pacote completo com benefícios exclusivos inclusos sem nenhum custo adicional no checkout.",
  },
  {
    id: "desc_5",
    category: "💰 Desconto & Economia",
    tag: "Preço de Fábrica",
    headline: "💵 PREÇO DIRETO DE FÁBRICA: Oportunidade perfeita para economizar!",
    subheadline: "Tabela especial com descontos progressivos e condições de pagamento altamente facilitadas.",
  },
  {
    id: "desc_6",
    category: "💰 Desconto & Economia",
    tag: "Até 50% OFF",
    headline: "🏷️ ATÉ 50% DE DESCONTO: A promoção que você esperava finalmente chegou!",
    subheadline: "Descontos reais aplicados em todo o catálogo selecionado. Toque abaixo e aproveite agora.",
  },
  {
    id: "desc_7",
    category: "💰 Desconto & Economia",
    tag: "Custo-Benefício",
    headline: "🤑 PREÇO ARRASADOR: Qualidade máxima pelo melhor custo-benefício!",
    subheadline: "Invista com segurança em um produto aprovado por especialistas e recomendado por centenas de clientes.",
  },
  {
    id: "desc_8",
    category: "💰 Desconto & Economia",
    tag: "Parcelamento Sem Juros",
    headline: "💳 CONDIÇÃO ESPECIAL NO PIX OU PARCELADO: Cabe no seu orçamento!",
    subheadline: "Desconto máximo no PIX à vista ou parcele em até 12x sem complicação no cartão de crédito.",
  },
  {
    id: "desc_9",
    category: "💰 Desconto & Economia",
    tag: "Corte de Preço",
    headline: "💸 NUNCA ESTEVE TÃO BARATO: Aproveite esse corte especial de valor!",
    subheadline: "Uma oferta calculada para entregar a melhor experiência pelo menor investimento possível.",
  },
  {
    id: "desc_10",
    category: "💰 Desconto & Economia",
    tag: "Black Friday",
    headline: "🛍️ CONDIÇÃO DE BLACK FRIDAY ANTECIPADA: Desconto agressivo no link!",
    subheadline: "Não espere pelo final do mês. As melhores ofertas do ano estão disponíveis agora mesmo.",
  },

  // 3. Exclusividade & Grupo VIP (10 modelos)
  {
    id: "vip_1",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Acesso VIP",
    headline: "👑 CONDIÇÃO VIP EXCLUSIVA: Liberada apenas para membros do grupo!",
    subheadline: "Você faz parte de uma lista seleta. Toque no botão e aproveite seu desconto reservado com exclusividade.",
  },
  {
    id: "vip_2",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Oferta Secreta",
    headline: "🔒 OFERTA FECHADA NO WHATSAPP: Não divulgada em redes públicas!",
    subheadline: "Esta página é privada e foi gerada especialmente para os membros ativos de nossa comunidade.",
  },
  {
    id: "vip_3",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Edição Especial",
    headline: "🌟 EDIÇÃO ESPECIAL LIMITADA: Produto campeão de vendas com bônus VIP!",
    subheadline: "Apenas clientes prioritários têm acesso a esse pacote com brindes e vantagens exclusivas.",
  },
  {
    id: "vip_4",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Acesso Antecipado",
    headline: "💎 ACESSO ANTECIPADO: Você está recebendo antes do lançamento geral!",
    subheadline: "Garanta o seu antes que o público em geral tenha acesso e o estoque inicial se esgote.",
  },
  {
    id: "vip_5",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Mais Querido",
    headline: "🏆 O QUERIDINHO DOS MEMBROS: Nosso produto mais elogiado do grupo!",
    subheadline: "Comprovado por centenas de pessoas do grupo. Veja como transformar sua rotina hoje mesmo.",
  },
  {
    id: "vip_6",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Lista Oculta",
    headline: "🎩 OFERTA RESTRITA: Desconto reservado diretamente para você!",
    subheadline: "Condição válida exclusivamente através deste link compartilhado com a nossa lista de contatos VIP.",
  },
  {
    id: "vip_7",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Padrão Ouro",
    headline: "✨ PADRÃO PREMIUM: Para quem não abre mão da máxima qualidade!",
    subheadline: "Materiais nobres, acabamento impecável e alta durabilidade testada e aprovada.",
  },
  {
    id: "vip_8",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Personalizado",
    headline: "🎯 SELEÇÃO PERSONALIZADA: A melhor escolha para os membros do grupo!",
    subheadline: "Reunimos as opções mais pedidas da semana em uma condição que você não encontra em outro lugar.",
  },
  {
    id: "vip_9",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Aprovação 100%",
    headline: "🥇 A ESCOLHA CERTA: 100% aprovado pelos clientes mais exigentes!",
    subheadline: "Junte-se a milhares de clientes satisfeitos que transformaram suas experiências com este produto.",
  },
  {
    id: "vip_10",
    category: "👑 Exclusividade & Grupo VIP",
    tag: "Comunidade VIP",
    headline: "🚀 VANTAGEM DE MEMBRO: Desconto especial liberado com um toque!",
    subheadline: "Agradecemos sua presença em nosso grupo VIP. Esse benefício foi preparado sob medida para você.",
  },

  // 4. Lançamento & Novidade (10 modelos)
  {
    id: "lan_1",
    category: "🚀 Lançamento & Novidade",
    tag: "Grande Lançamento",
    headline: "🚀 GRANDE LANÇAMENTO: A nova versão mais esperada do ano chegou!",
    subheadline: "Com tecnologia aprimorada e design moderno, conheça a nova linha com valor promocional de estreia.",
  },
  {
    id: "lan_2",
    category: "🚀 Lançamento & Novidade",
    tag: "Novidade da Semana",
    headline: "✨ NOVIDADE EXCLUSIVA: Descubra a evolução que vai superar suas expectativas!",
    subheadline: "Desenvolvido com base no feedback dos clientes para entregar máxima performance e praticidade.",
  },
  {
    id: "lan_3",
    category: "🚀 Lançamento & Novidade",
    tag: "Lote 1 de Lançamento",
    headline: "📦 LOTE 1 LIBERADO: Seja um dos primeiros a garantir a nova edição!",
    subheadline: "O primeiro lote conta com valor especial de lançamento e bônus surpresa no envio.",
  },
  {
    id: "lan_4",
    category: "🚀 Lançamento & Novidade",
    tag: "Inovação Total",
    headline: "💡 A MAIS RECENTE INOVAÇÃO: O upgrade perfeito que você precisava!",
    subheadline: "Diga adeus a soluções antigas. Experimente o novo padrão de eficiência e praticidade do mercado.",
  },
  {
    id: "lan_5",
    category: "🚀 Lançamento & Novidade",
    tag: "Tendência Global",
    headline: "🔥 A TENDÊNCIA DO MOMENTO: O produto que viralizou agora no Brasil!",
    subheadline: "Sucesso internacional finalmente disponível para pronta entrega com frete rápido e seguro.",
  },
  {
    id: "lan_6",
    category: "🚀 Lançamento & Novidade",
    tag: "Pré-Venda VIP",
    headline: "🎯 PRÉ-ESTREIA EXCLUSIVA: Condições válidas somente para os pioneiros!",
    subheadline: "Compre antes de todo mundo e garanta as melhores unidades com condições financeiras facilitadas.",
  },
  {
    id: "lan_7",
    category: "🚀 Lançamento & Novidade",
    tag: "Design Renovado",
    headline: "💎 NOVO DESIGN & PERFORMANCE: Máxima elegância com eficácia comprovada!",
    subheadline: "Cada detalhe foi pensado para proporcionar a melhor experiência de uso no seu dia a dia.",
  },
  {
    id: "lan_8",
    category: "🚀 Lançamento & Novidade",
    tag: "Coleção Nova",
    headline: "🌟 NOVA COLEÇÃO DISPONÍVEL: Modelos exclusivos prontos para envio!",
    subheadline: "Confira as novidades em primeira mão e selecione a sua opção favorita antes do estoque geral abrir.",
  },
  {
    id: "lan_9",
    category: "🚀 Lançamento & Novidade",
    tag: "Versão Atualizada",
    headline: "⚡ NOVA VERSÃO ATUALIZADA: Mais rápida, resistente e eficiente!",
    subheadline: "Tudo o que você já gostava, agora aprimorado com materiais de alta durabilidade e acabamento superior.",
  },
  {
    id: "lan_10",
    category: "🚀 Lançamento & Novidade",
    tag: "Exclusivo de Lançamento",
    headline: "🎁 OFERTA DE ESTREIA: Compre o lançamento e ganhe benefícios exclusivos!",
    subheadline: "Bônus especial de boas-vindas liberado apenas durante os primeiros dias de lançamento oficial.",
  },

  // 5. Garantia & Confiança (10 modelos)
  {
    id: "gar_1",
    category: "🛡️ Garantia & Confiança",
    tag: "Compra Segura",
    headline: "🛡️ COMPRA 100% SEGURA & PROTEGIDA: Garantia total de satisfação!",
    subheadline: "Seus dados estão protegidos e sua compra é garantida do pedido até a entrega final na sua porta.",
  },
  {
    id: "gar_2",
    category: "🛡️ Garantia & Confiança",
    tag: "Avaliação Máxima",
    headline: "⭐ PRODUTO 5 ESTRELAS: Recomendado por centenas de clientes satisfeitos!",
    subheadline: "Confira as avaliações reais de quem já comprou, testou e aprovou nossos produtos e atendimento.",
  },
  {
    id: "gar_3",
    category: "🛡️ Garantia & Confiança",
    tag: "Satisfação Garantida",
    headline: "🤝 SATISFAÇÃO GARANTIDA: Ame o seu produto ou receba suporte imediato!",
    subheadline: "Nosso compromisso é com a sua total felicidade e tranquilidade em cada detalhe da compra.",
  },
  {
    id: "gar_4",
    category: "🛡️ Garantia & Confiança",
    tag: "Envio Rápido",
    headline: "🚚 ENVIO IMEDIATO E RASTREADO: Receba com rapidez no seu endereço!",
    subheadline: "Despachamos em até 24h úteis com código de rastreio enviado diretamente no seu WhatsApp.",
  },
  {
    id: "gar_5",
    category: "🛡️ Garantia & Confiança",
    tag: "Original com Nota",
    headline: "✅ PRODUTO 100% ORIGINAL: Procedência comprovada e garantia oficial!",
    subheadline: "Trabalhamos apenas com itens autênticos, novos, lacrados de fábrica e com procedência atestada.",
  },
  {
    id: "gar_6",
    category: "🛡️ Garantia & Confiança",
    tag: "Suporte no WhatsApp",
    headline: "💬 ATENDIMENTO HUMANO NO WHATSAPP: Tire dúvidas em tempo real!",
    subheadline: "Nossa equipe de suporte está de prontidão para te atender, tirar dúvidas e acompanhar seu pedido.",
  },
  {
    id: "gar_7",
    category: "🛡️ Garantia & Confiança",
    tag: "Blindagem de Pagamento",
    headline: "🔒 TRANSAÇÃO BLINDADA: Pague com total segurança e sigilo bancário!",
    subheadline: "Aceitamos as principais bandeiras de cartão, PIX e boleto com tecnologia de criptografia de ponta a ponta.",
  },
  {
    id: "gar_8",
    category: "🛡️ Garantia & Confiança",
    tag: "Cuidado no Envio",
    headline: "📦 EMBALAGEM REFORÇADA: Seu produto chega impecável e protegido!",
    subheadline: "Cuidamos de cada pacote com proteções antichoque para garantir que chegue em perfeito estado.",
  },
  {
    id: "gar_9",
    category: "🛡️ Garantia & Confiança",
    tag: "Garantia Estendida",
    headline: "📜 GARANTIA DE FÁBRICA: Segurança completa do início ao pós-venda!",
    subheadline: "Conte com nossa assessoria completa caso precise de suporte técnico ou trocas no pós-compra.",
  },
  {
    id: "gar_10",
    category: "🛡️ Garantia & Confiança",
    tag: "Líder de Mercado",
    headline: "🎖️ RECONHECIMENTO & TRADIÇÃO: Atendimento sério e entrega 100% garantida!",
    subheadline: "Mais de anos de atuação no mercado oferecendo as melhores soluções com credibilidade e transparência.",
  },
];

