export interface TestimonialPreset {
  id: string;
  name: string;
  comment: string;
  stars: number;
  category?: string;
  role?: string;
}

export const TESTIMONIAL_CATEGORIES = [
  "Todos",
  "Economia & Descontos",
  "Lançamentos & Exclusividade",
  "Entrega Rápida & Agilidade",
  "Qualidade & Confiança",
  "Atendimento & Suporte",
  "Praticidade & Facilidade",
] as const;

export const HUMANIZED_TESTIMONIALS_POOL: TestimonialPreset[] = [
  // --- 1. Economia & Descontos (1 a 25) ---
  {
    id: "testi_1",
    name: "Lucas M.",
    comment: "Economizei muito entrando no grupo VIP! Os descontos são reais e chegam antes de todo mundo.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_2",
    name: "Gabriel T.",
    comment: "Consegui um desconto exclusivo no PIX que não tinha no site. Super recomendo!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_3",
    name: "Marcelo N.",
    comment: "As ofertas relâmpago são muito boas. Já economizei mais de R$ 300 só neste mês.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_4",
    name: "Felipe A.",
    comment: "Peguei uma queima de estoque com frete grátis que valeu cada centavo. Muito top!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_5",
    name: "Renata D.",
    comment: "Amei a experiência! O cupom de boas-vindas do grupo VIP funcionou perfeitamente.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_6",
    name: "Bruno C.",
    comment: "O valor com desconto do grupo VIP cobriu com folga o frete. Vale muito a pena ficar atento.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_7",
    name: "Patricia G.",
    comment: "Comprei 3 itens pelo preço de 2 na promoção relâmpago que soltaram de manhã!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_8",
    name: "Vinícius S.",
    comment: "Condições de parcelamento sem juros direto pelo link VIP. Sensacional!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_9",
    name: "Julio C.",
    comment: "Preço muito abaixo do mercado tradicional. Não compro mais fora desse grupo.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_10",
    name: "Fernanda L.",
    comment: "A economia foi real. Comparei com grandes lojas e aqui saiu 35% mais barato.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_11",
    name: "Gustavo B.",
    comment: "Promoção exclusiva de madrugada me garantiu o melhor preço do ano.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_12",
    name: "Aline F.",
    comment: "Peguei o combo com frete promocional e ainda ganhei brinde surpresa. Perfeito!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_13",
    name: "Marcos V.",
    comment: "Cupom secreto liberado só para quem estava no grupo. Deu 20% off na hora!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_14",
    name: "Sabrina T.",
    comment: "Já comprei para a família toda aproveitando as ofertas diárias do grupo.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_15",
    name: "Leandro O.",
    comment: "A melhor black friday antecipada que já participei foi nesse grupo VIP.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_16",
    name: "Carla Z.",
    comment: "Desconto no PIX aprovado na hora sem burocracia nenhuma. Economia garantida.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_17",
    name: "Danilo P.",
    comment: "Os preços postados aqui são realmente diferenciados, sem pegadinha.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_18",
    name: "Priscila M.",
    comment: "Economizei mais de 150 reais no meu primeiro pedido pelo grupo. Indico demais!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_19",
    name: "Henrique G.",
    comment: "Descontos agressivos de verdade. Quem não está no grupo está perdendo dinheiro.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_20",
    name: "Talita R.",
    comment: "Preço de atacado em compras unitárias através das promoções semanais.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_21",
    name: "Eduardo X.",
    comment: "Entrei desconfiado, mas o primeiro cupom já pagou a minha atenção. Muito top!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_22",
    name: "Vanessa K.",
    comment: "Ofertas com cashback e desconto direto que superaram todas as expectativas.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_23",
    name: "Robson J.",
    comment: "Consegui fechar uma compra com desconto que eu estava namorando há 3 meses.",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_24",
    name: "Monique S.",
    comment: "Tabela promocional com preços de custo para membros ativos do grupo!",
    stars: 5,
    category: "Economia & Descontos",
  },
  {
    id: "testi_25",
    name: "Anderson N.",
    comment: "Custo-benefício imbatível. A cada alerta eu consigo poupar uma boa grana.",
    stars: 5,
    category: "Economia & Descontos",
  },

  // --- 2. Lançamentos & Exclusividade (26 a 50) ---
  {
    id: "testi_26",
    name: "Camila R.",
    comment: "Comprei lançamentos antes de esgotar o estoque. Vale muito a pena, recomendo demais!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_27",
    name: "Larissa C.",
    comment: "Aviso de reposição em primeira mão salvou minhas compras. Excelente iniciativa!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_28",
    name: "Diego K.",
    comment: "Sensacional! Fico sempre de olho nas notificações do grupo para não perder nenhuma oportunidade.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_29",
    name: "Amanda V.",
    comment: "Consegui a edição limitada graças ao aviso antecipado enviado no grupo.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_30",
    name: "Igor M.",
    comment: "Acesso antecipado aos melhores produtos antes de abrirem para o público geral.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_31",
    name: "Jéssica F.",
    comment: "Estoque acabou em minutos no site aberto, mas pelo link VIP consegui garantir o meu!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_32",
    name: "Matheus D.",
    comment: "Produtos exclusivos que não aparecem na vitrine comum da loja. Show!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_33",
    name: "Bruna E.",
    comment: "Receber a lista de novidades antes de todo mundo faz toda a diferença.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_34",
    name: "Cássio L.",
    comment: "Prioridade na fila de pedidos para quem faz parte do grupo VIP. Nota 10!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_35",
    name: "Tatiane M.",
    comment: "Avisaram 1 hora antes de abrir as vendas gerais e garantiu minha compra com tranquilidade.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_36",
    name: "Guilherme S.",
    comment: "Pré-venda exclusiva sem passar aperto ou fila virtual travando.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_37",
    name: "Letícia P.",
    comment: "Coleção nova reservada com desconto de pré-estreia. Incrível!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_38",
    name: "Renan B.",
    comment: "Sempre que chega novidade os administradores soltam fotos reais e vídeos no grupo.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_39",
    name: "Bianca R.",
    comment: "Sensação de exclusividade total. Fico por dentro de tudo em primeira mão.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_40",
    name: "Wagner C.",
    comment: "Modelos exclusivos importados que eu não encontrava em lugar nenhum no Brasil.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_41",
    name: "Natália O.",
    comment: "Aviso de restock me permitiu comprar o produto mais disputado do ano!",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_42",
    name: "Fábio R.",
    comment: "O privilégio de comprar antes dos estoques zerarem compensa demais estar aqui.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_43",
    name: "Kelly S.",
    comment: "Lotes promocionais com vagas limitadas. Fui rápida e garanti o meu desconto.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_44",
    name: "Leonardo F.",
    comment: "Informações técnicas detalhadas antes de qualquer anúncio público.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_45",
    name: "Isabela G.",
    comment: "Comprei o lançamento do momento com frete prioritário pelo link do grupo.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_46",
    name: "Caio H.",
    comment: "Grupo focado em novidades quentes do mercado sem enrolação.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_47",
    name: "Débora N.",
    comment: "Sempre que quero um produto exclusivo, sei que aqui sai primeiro.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_48",
    name: "Rogério M.",
    comment: "A experiência de ser tratado como cliente VIP desde o primeiro anúncio é sensacional.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_49",
    name: "Carolyne T.",
    comment: "As melhores seleções de produtos antes de viralizarem nas redes.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },
  {
    id: "testi_50",
    name: "Breno L.",
    comment: "Notificações precisas de lançamentos que me fazem economizar tempo e dinheiro.",
    stars: 5,
    category: "Lançamentos & Exclusividade",
  },

  // --- 3. Entrega Rápida & Agilidade (51 a 75) ---
  {
    id: "testi_51",
    name: "Beatriz L.",
    comment: "Já é a terceira vez que compro direto pelo grupo. Entrega rápida e produto impecável.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_52",
    name: "Aline V.",
    comment: "Chegou super rápido aqui em casa, tudo muito bem embalado. Nota mil!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_53",
    name: "Tiago M.",
    comment: "Comprei na terça e na quinta de manhã já estava na minha porta. Agilidade surreal!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_54",
    name: "Raquel D.",
    comment: "Código de rastreio enviado no mesmo dia da confirmação do pagamento.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_55",
    name: "Otávio F.",
    comment: "Embalagem reforçada, produto 100% protegido e entrega antes do prazo previsto.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_56",
    name: "Cristiane B.",
    comment: "O envio expresso para membros do grupo realmente funciona. Chegou voando!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_57",
    name: "Samuel G.",
    comment: "Fiz o pedido na sexta e na segunda já estava testando. Parabéns pela logística!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_58",
    name: "Marina K.",
    comment: "Tudo bem protegido com plástico bolha e caixa lacrada. Muito capricho!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_59",
    name: "Douglas P.",
    comment: "A agilidade no despacho do produto superou qualquer outra loja online.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_60",
    name: "Elaine S.",
    comment: "Moro no interior e mesmo assim a encomenda chegou em tempo recorde.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_61",
    name: "Fábio H.",
    comment: "Rastreamento atualizado passo a passo sem sustos pelo caminho.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_62",
    name: "Gisele C.",
    comment: "Pedido despachado poucas horas após fechar pelo WhatsApp. Recomendo de olhos fechados!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_63",
    name: "Hugo R.",
    comment: "Chegou perfeito e antes da data prometida. Comprarei novamente com certeza.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_64",
    name: "Ingrid M.",
    comment: "Muito rápido! A transportadora entregou em 48 horas aqui em SP.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_65",
    name: "João Pedro A.",
    comment: "A logística deles é impecável, recebi tudo nos trinques e super veloz.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_66",
    name: "Karina T.",
    comment: "Embalagem discreta, segura e entrega muito antes do esperado.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_67",
    name: "Luciano E.",
    comment: "Despacho no mesmo dia útil! Fazia tempo que não via um serviço tão ágil.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_68",
    name: "Mirian G.",
    comment: "Tudo certinho, veio com manual, nota e muito bem condicionado.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_69",
    name: "Nilton S.",
    comment: "Velocidade na entrega que dá inveja nos maiores marketplaces do país.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_70",
    name: "Olívia P.",
    comment: "Entrega segura, com confirmação por SMS e aviso de saída para entrega.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_71",
    name: "Paulo R.",
    comment: "Tudo perfeito do momento que paguei até o carteiro tocar a campainha.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_72",
    name: "Quézia M.",
    comment: "Rapidez que me salvou para dar um presente de aniversário a tempo!",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_73",
    name: "Renato D.",
    comment: "Prazo de 7 dias úteis que chegou em apenas 3 dias corridos.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_74",
    name: "Silvia L.",
    comment: "Transportadora parceira super pontual e atenciosa na entrega.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },
  {
    id: "testi_75",
    name: "Tales O.",
    comment: "Despacho veloz e produto entregue sem nenhum amassado na caixa.",
    stars: 5,
    category: "Entrega Rápida & Agilidade",
  },

  // --- 4. Qualidade & Confiança (76 a 100) ---
  {
    id: "testi_76",
    name: "Rafael B.",
    comment: "Preço justo e produtos 100% originais. Podem entrar no grupo sem medo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_77",
    name: "Juliana P.",
    comment: "Fiquei com receio no começo, mas o suporte é super atencioso e o produto chegou perfeito.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_78",
    name: "Thiago H.",
    comment: "Ambiente organizado e sem conversa fiada, direto ao ponto com os melhores preços.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_79",
    name: "Arthur M.",
    comment: "Qualidade acima da média! Produto original com garantia direto do fornecedor.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_80",
    name: "Camila B.",
    comment: "Confiabilidade total. Já fiz 4 compras e todas vieram em estado impecável.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_81",
    name: "Danilo S.",
    comment: "Sem surpresas ruins. O que mostram nas fotos é exatamente o que chega.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_82",
    name: "Eduarda R.",
    comment: "Empresa séria e transparente. Passa muita segurança em cada negociação.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_83",
    name: "Flávio T.",
    comment: "Material de altíssima qualidade. O acabamento me surpreendeu positivamente.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_84",
    name: "Giovanna P.",
    comment: "Tinha medo de comprar pela internet, mas a reputação do grupo é merecida.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_85",
    name: "Heitor N.",
    comment: "Garantia de procedência e nota fiscal emitida no ato da compra. Nota 10.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_86",
    name: "Iara C.",
    comment: "Qualidade premium de verdade. Virei cliente fiel e já indiquei para os amigos.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_87",
    name: "Jonas V.",
    comment: "Fiel às especificações técnicas descritas no anúncio do grupo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_88",
    name: "Kátia M.",
    comment: "Produto lacrado de fábrica, tudo original e funcionando 100%.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_89",
    name: "Lucas E.",
    comment: "Honestidade e clareza nas informações. Difícil achar empresas assim hoje.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_90",
    name: "Maíra G.",
    comment: "Superou todas as minhas expectativas em durabilidade e acabamento.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_91",
    name: "Nelson F.",
    comment: "Atende exatamente ao que promete. Produto robusto e muito bem construído.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_92",
    name: "Otávia R.",
    comment: "Segurança no pagamento e garantia de satisfação comprovada.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_93",
    name: "Pedro Henrique L.",
    comment: "Excelente padrão de controle de qualidade antes do envio.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_94",
    name: "Quênia S.",
    comment: "Produto maravilhoso, acabamento sofisticado e originalidade certificada.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_95",
    name: "Roberto C.",
    comment: "Comprei de olhos fechados por recomendação de um colega e não me arrependo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_96",
    name: "Sandra D.",
    comment: "Transparência total nos preços e nas condições. Podem confiar sem medo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_97",
    name: "Túlio B.",
    comment: "Melhor investimento que fiz este ano. Qualidade que dura de verdade.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_98",
    name: "Ursula K.",
    comment: "Padrão de qualidade impecável, atendimento ético e produto legítimo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_99",
    name: "Valmir M.",
    comment: "Empresa nota 10 no Reclame Aqui e aqui no grupo mantêm o mesmo nível.",
    stars: 5,
    category: "Qualidade & Confiança",
  },
  {
    id: "testi_100",
    name: "Wesley A.",
    comment: "Recebi o produto com certificado e selo de autenticidade. Vale cada centavo.",
    stars: 5,
    category: "Qualidade & Confiança",
  },

  // --- 5. Atendimento & Suporte (101 a 125) ---
  {
    id: "testi_101",
    name: "Rodrigo F.",
    comment: "Atendimento no WhatsApp é nota 10. Tirei dúvidas de entrega e fechei no mesmo dia.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_102",
    name: "Mariana S.",
    comment: "Melhor grupo que já entrei. Sem spam, só postam promoções boas de verdade.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_103",
    name: "Alexandre G.",
    comment: "O suporte tirou minhas dúvidas em menos de 5 minutos. Atendimento humanizado e rápido!",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_104",
    name: "Bárbara N.",
    comment: "Fui super bem orientada na escolha do modelo ideal para a minha necessidade.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_105",
    name: "Cláudio R.",
    comment: "Equipe educada e muito prestativa. Resolveram uma troca com total agilidade.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_106",
    name: "Daniela F.",
    comment: "O pós-venda deles é o grande diferencial. Me acompanharam até a entrega final.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_107",
    name: "Erick V.",
    comment: "Grupo silencioso onde apenas os administradores mandam ofertas. Zero poluição!",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_108",
    name: "Fabiana P.",
    comment: "Atendentes muito bem treinados, entendem do produto de verdade.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_109",
    name: "Gilberto S.",
    comment: "Respostas claras e sem aquelas mensagens automáticas de robô que não resolvem nada.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_110",
    name: "Helena T.",
    comment: "Precisei tirar uma dúvida no sábado à tarde e fui atendida prontamente. Sensacional!",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_111",
    name: "Ivan D.",
    comment: "Profissionalismo do início ao fim. Dá gosto de comprar com gente tão atenciosa.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_112",
    name: "Joana M.",
    comment: "Me ajudaram a aplicar o cupom VIP certinho no checkout. Muito prestativos!",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_113",
    name: "Kleber L.",
    comment: "Atendimento direto pelo WhatsApp com pessoas reais. Isso faz toda a diferença.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_114",
    name: "Luana C.",
    comment: "Grupo muito bem moderado, sem bate-papo desnecessário, direto nas melhores ofertas.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_115",
    name: "Murilo B.",
    comment: "Atenção aos detalhes e muita paciência para explicar cada benefício do produto.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_116",
    name: "Nicole R.",
    comment: "Suporte nota mil! Tive um imprevisto no endereço e corrigiram na hora antes do envio.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_117",
    name: "Osvaldo G.",
    comment: "Experiência de atendimento personalizada de verdade. Recomendo a todos!",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_118",
    name: "Poliana S.",
    comment: "Gostei muito da rapidez no atendimento quando chamei no privado para tirar dúvidas.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_119",
    name: "Rômulo F.",
    comment: "Sem burocracia, atendimento ágil e focado na solução do cliente.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_120",
    name: "Samara E.",
    comment: "Disseram o prazo certinho e cumpriram à risca. Comunicação impecável.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_121",
    name: "Tadeu K.",
    comment: "Excelente canal de suporte. Nunca fiquei no vácuo em nenhuma pergunta.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_122",
    name: "Viviane N.",
    comment: "Sentimento de acolhimento e confiança total ao conversar com os consultores.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_123",
    name: "Washington P.",
    comment: "Organização exemplar no grupo e suporte individual de primeira qualidade.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_124",
    name: "Yasmin C.",
    comment: "Tratamento VIP do primeiro 'olá' até a entrega do pacote em casa.",
    stars: 5,
    category: "Atendimento & Suporte",
  },
  {
    id: "testi_125",
    name: "Zélia M.",
    comment: "Tirei todas as dúvidas antes de pagar e a atendente foi um amor de pessoa.",
    stars: 5,
    category: "Atendimento & Suporte",
  },

  // --- 6. Praticidade & Facilidade (126 a 150) ---
  {
    id: "testi_126",
    name: "Alan S.",
    comment: "Compra feita em 2 cliques direto pelo link do WhatsApp. Muito prático!",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_127",
    name: "Brenda K.",
    comment: "Não preciso ficar procurando cupons na internet, eles mandam tudo mastigado.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_128",
    name: "César T.",
    comment: "Interface limpa, checkout rápido e opção de PIX com aprovação instantânea.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_129",
    name: "Daniele L.",
    comment: "Facilidade incrível para comprar no meio da correria do trabalho pelo celular.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_130",
    name: "Evandro G.",
    comment: "Links diretos para o produto já com o desconto aplicado, sem precisar digitar código.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_131",
    name: "Franciele R.",
    comment: "Economizo tempo e dinheiro sem complicação. Vale cada segundo no grupo.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_132",
    name: "Geraldo M.",
    comment: "Processo de compra mais descomplicado que já utilizei na vida.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_133",
    name: "Heloísa P.",
    comment: "Apenas clico no link do grupo e finalizo no PIX em menos de 1 minuto.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_134",
    name: "Ismael B.",
    comment: "Zero burocracia, sem cadastros longos ou páginas lentas travando.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_135",
    name: "Joyce V.",
    comment: "Receber a oferta pronta no celular enquanto tomo café é maravilhoso.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_136",
    name: "Kauê F.",
    comment: "Checkout fluido e seguro. Minha compra favorita do mês!",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_137",
    name: "Lívia O.",
    comment: "Mudo para outros grupos e sempre volto para esse pela facilidade de navegação.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_138",
    name: "Moisés D.",
    comment: "Tudo bem sintetizado: foto, preço normal, preço VIP e link de compra rápida.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_139",
    name: "Nayara C.",
    comment: "Sem enrolação, links 100% seguros e que vão direto para a oferta real.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_140",
    name: "Otávio J.",
    comment: "Muito simples de usar, até meus pais que têm dificuldade conseguiram comprar sozinhos.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_141",
    name: "Paloma S.",
    comment: "Recebo o alerta, clico e em dois toques a confirmação chega no meu e-mail.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_142",
    name: "Queiroz N.",
    comment: "Plataforma super intuitiva e adaptada para celulares antigos sem travar.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_143",
    name: "Rebeca H.",
    comment: "Facilidade de pagamento com cartão em até 12x ou desconto no PIX instantâneo.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_144",
    name: "Sérgio W.",
    comment: "O melhor grupo de compras do WhatsApp. Prático, limpo e direto ao ponto.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_145",
    name: "Thais G.",
    comment: "Comprei pelo link do grupo enquanto estava no trânsito, super rápido e seguro.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_146",
    name: "Ueliton R.",
    comment: "Zero complicações na hora de fechar o pedido. Nota máxima em usabilidade.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_147",
    name: "Vera Lúcia P.",
    comment: "Adorei a clareza dos anúncios. Sem letras miúdas ou taxas escondidas.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_148",
    name: "William K.",
    comment: "Comodidade total de acompanhar preços em tempo real direto na palma da mão.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_149",
    name: "Ximena T.",
    comment: "Notificações na medida certa, sem sobrecarregar o WhatsApp e sempre relevantes.",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
  {
    id: "testi_150",
    name: "Yuri F.",
    comment: "Excelente experiência de ponta a ponta. Prático, confiável e muito econômico!",
    stars: 5,
    category: "Praticidade & Facilidade",
  },
];

/**
 * Retorna uma quantidade N de depoimentos sorteados aleatoriamente entre os ativos
 */
export function getRandomTestimonials(
  count: number = 2,
  activeIds?: string[] | null
): TestimonialPreset[] {
  let pool = HUMANIZED_TESTIMONIALS_POOL;
  if (Array.isArray(activeIds) && activeIds.length > 0) {
    const set = new Set(activeIds);
    const filtered = pool.filter((item) => set.has(item.id));
    if (filtered.length > 0) {
      pool = filtered;
    }
  }
  const shuffled = [...pool].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.max(1, Math.min(count, pool.length)));
}
